# .github/workflows/tofu.yml
name: 'TOFU GKE and ArgoCD Deploy'

on:
  push:
    branches:
      - main
      - develop
      - 'gke-demos'

jobs:
  tofu:
    name: 'TOFU Apply'
    runs-on: ubuntu-latest

    env:
      TOFU_ENV: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'develop' && 'stage' || 'sandbox' }}
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Set up Google Cloud SDK'
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: 'Set up OpenTofu'
      uses: opentofu/setup-opentofu@v1

    - name: 'TOFU Format Check'
      run: |
        echo "Running TOFU fmt..."
        tofu fmt -check

    - name: 'TOFU Init with Partial Backend Configuration'
      run: |
        echo "Initializing TOFU..."
        echo "${{ secrets.GCP_SA_KEY }}" > key.json
        tofu init -backend-config="bucket=${{ secrets.GCS_BUCKET_NAME }}" \
                  -backend-config="credentials=key.json" \
                  -backend-config="prefix=tofu/state/${{ env.TOFU_ENV }}"
        rm -f key.json

    - name: 'TOFU Plan'
      run: |
        echo "Running TOFU plan for environment: ${{ env.TOFU_ENV }}"
        tofu plan -var-file="${{ env.TOFU_ENV }}.tfvars" -out=tfplan

    - name: 'TOFU Apply'
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: |
        echo "Applying TOFU changes for environment: ${{ env.TOFU_ENV }}"
        # tofu apply tfplan

